# -*- coding: utf-8 -*-
# PS case-study source data. body = ordered list of render-specs:
#   ('h2', text) ('h3', text) ('p', html) ('comment', text) ('ul', [items])
#   ('raw', html) ('pull', eyebrow, html) ('quote', text, name, role, company)
# Sector / Platform / sub-voice / pull eyebrows are EDITORIAL derivations (flag for JP).

# Registry for next-case cards: slug -> (card eyebrow, headline). Includes already-published.
CARD = {
  'energizer': ('Digital · Energizer', 'Validating a new product in 30 days, so the expensive mistakes never got made'),
  'xyon': ('Digital · XYON Health', "A men's health brand, launched as a full consultation-to-purchase commerce engine"),
  'allia-health-group': ('Digital · Allia Health Group', 'A multi-brand health portfolio, rebranded and rebuilt as one investor-ready platform'),
  'case-telus-koodo': ('Digital · TELUS &amp; Koodo', 'One platform that ended USB-stick ordering for a national dealer network'),
  'hall-constructors': ('Digital · Hall Constructors', 'A digital ticketing system foremen actually use, where the last one failed'),
  'ncis-maritime': ('Digital · NCIS', 'Maritime intelligence pulled out of legacy silos and into one fast investigative view'),
  'telus-support': ('Digital · TELUS Support', "A self-serve redesign that took $600K out of the first year's support costs"),
  'luxxee': ('Digital · luxxee', "We didn't just build the product. We co-founded it, equity and all"),
  'bc-parks-foundation': ('Digital · BC Parks Foundation', 'Rescuing a launch that had already failed once'),
  '5x5': ('Digital · 5x5 Technologies', "A website that didn't just tell the story, it showed it — built for the fundraise"),
  'phinity': ('Digital · Phinity', 'A pool-care giant tested a direct-to-consumer model, and it became the business'),
  'nva': ('Digital · NVA', 'One brand story across 1,000+ hospitals, without flattening any of them'),
  'bcw': ('Digital · BC Women’s Health Foundation', 'A research report turned into a campaign that hit the news'),
  'delta-controls': ('Digital · Delta Controls', 'Sensor setup that took 5 minutes now takes 90 seconds'),
  'angel-oak-home-loans': ('Digital · Angel Oak Home Loans', 'A site rebuilt around how people actually borrow, with leads to match'),
  'telus-rewards': ('Digital · TELUS Rewards', 'The loyalty blueprint that launched 22% ahead of target'),
}

CASES = [
{
  'slug': 'hall-constructors',
  'title': 'Hall Constructors Case Study — Digital Ticketing App | POWER SHIFTER',
  'meta': 'How POWER SHIFTER built Hall Constructors a rugged digital truck-ticketing system foremen actually adopted — where an earlier attempt had failed on the job site.',
  'eyebrow': 'Digital · Hall Constructors',
  'h1': 'A digital ticketing system foremen actually use, where the last one failed',
  'subvoice': "A paper ticket they'd already failed to replace once — rebuilt to survive dust, glare, rain, and the foremen's skepticism.",
  'role': 'Product management · UX research &amp; design · UI design · Web development',
  'cat': 'Digital', 'client': 'Hall Constructors', 'sector': 'Construction · Field operations',
  'services': 'Product management · UX research &amp; design · UI design · Web development · PM · QA',
  'platform': 'iPad-first web app',
  'body': [
    ('h2', 'the brief.'),
    ('p', "Hall Constructors ran truck load management on paper — forms that got lost, smudged, and miscounted, turning into billing errors and invoicing delays. They needed a rugged, genuinely easy digital system foremen would adopt in real construction conditions, one that accounted for outdoor glare, weather, and short training windows."),
    ('p', "And it had to overcome something harder than any of that: the memory of a previous digitization attempt that had failed on usability."),
    ('pull', 'Brief — the memory', 'Hall had already tried to kill the paper ticket once — <span class="mag">it didn\'t take</span>.'),
    ('h2', 'the challenge.'),
    ('p', 'Adoption was the whole game. Foremen working in dust, rain, and bright sun had already been handed a digital tool and rejected it — so the bar wasn\'t "build an app," it was "build the one they won\'t abandon." That meant designing for the worksite first and the screen second: high-contrast displays readable in direct sun, controls usable with work gloves, and workflows fast enough to beat reaching for a pen.'),
    ('h2', 'the process.'),
    ('p', "We started with the people, despite limited early access to foremen — interviewing stakeholders to pull out the functional must-haves, then building Figma prototypes around high-contrast screens, large touch targets, and stripped-down workflows. Critically, we tested those prototypes hands-on with foremen on iPads, in bright sunlight and rough conditions, and ran the feedback straight back into the design. Later phases put working versions on real job sites for final adjustments before launch, and we built a UI/UX design system so the app could grow without fragmenting."),
    ('h2', 'the solution.'),
    ('h3', 'a field-ready ticketing system.'),
    ('p', "We built a rugged, intuitive digital ticketing system for truck load management — high-contrast and easy to navigate on iPads, designed for the conditions it actually lives in. Data is captured digitally at the source, enabling near real-time reconciliation and faster invoicing, and a scalable design system keeps future features consistent."),
    ('h2', 'the outcome.'),
    ('p', "The system is in use by the foremen who rejected the last one — adoption after a prior failed attempt being the metric that matters most here."),
    ('p', "By capturing data digitally at the point of work, an entire class of errors structurally disappears: lost paper tickets and illegible handwriting can't corrupt invoicing when the count is recorded at source — which is what closes the gap between work done and work billed."),
    ('pull', 'Outcome — adoption', 'Lost tickets and illegible handwriting can\'t corrupt invoicing — <span class="mag">when the count is captured at the source</span>.'),
    ('comment', '[OUTCOME PLACEHOLDER — Notion Needs Review=YES. Tier 2 (qualitative). Ongoing-development relationship — strong candidate for a client data ask: tickets/month, days-to-invoice before vs. after, error-rate delta. Class 1/2/7. Internal marker — not rendered.]'),
  ],
  'next': ['ncis-maritime', 'delta-controls'],
},
{
  'slug': 'ncis-maritime',
  'title': 'NCIS Case Study — Maritime Intelligence Platform | POWER SHIFTER',
  'meta': "How POWER SHIFTER unified NCIS's siloed legacy systems into one fast maritime intelligence platform — real-time data and alerting for faster investigative decisions.",
  'eyebrow': 'Digital · NCIS',
  'h1': 'Maritime intelligence pulled out of legacy silos and into one fast investigative view',
  'subvoice': 'Maritime threat investigation moves at the speed of the slowest screen — so we took the interface out from between the analyst and the answer.',
  'role': 'User research · MVP scope · Technical architecture · UX/UI · Full-stack development',
  'cat': 'Digital', 'client': 'National Crime Investigative Services', 'sector': 'Defense · Maritime intelligence',
  'services': 'User interviews · Competitive research · MVP scope · Technical architecture · UX/UI · Full-stack development · API integration',
  'platform': 'Web platform · Real-time dashboard',
  'body': [
    ('h2', 'the brief.'),
    ('p', "National Crime Investigative Services builds technology for threat detection and intelligence, and faced an evolving global threat landscape that demanded real-time maritime situational awareness. The existing tooling was the obstacle: legacy systems to modernize, investigative workflows to streamline, and complex data from many sources that needed to come together into one platform — so international security teams could respond faster and act on clearer insight."),
    ('pull', 'Brief — the friction', 'Maritime threat investigation moves at <span class="mag">the speed of the slowest screen</span>.'),
    ('h2', 'the challenge.'),
    ('p', "The pain was operational. Cumbersome, disjointed legacy systems slowed every investigation; data silos blocked a single coherent view of a situation; and friction at the decision point hurt both speed and accuracy when accuracy mattered most. The job was to remove the interface from between the analyst and the answer."),
    ('h2', 'the process.'),
    ('p', "We ran in-depth user journey workshops with field agents and security analysts to understand the real moments of decision, then used a rapid prototyping sprint to test new workflows and interface concepts. The design work concentrated on simplifying data visualizations and streamlining the reporting process — the two places the old systems cost the most time."),
    ('h2', 'the solution.'),
    ('h3', 'a unified, high-speed intelligence platform.'),
    ('p', "We brought disparate data sources into a single, centralized dashboard, with advanced visualizations, mapping tools, and real-time threat alerting to make intelligence immediately actionable. The platform was engineered for speed at scale — fast-loading interfaces even with large datasets — and built responsive and mobile-friendly so investigations can happen in the field, not just at a desk."),
    ('h2', 'the outcome.'),
    ('p', "The platform is in production, consolidating previously siloed sources into one real-time view and accelerating investigative workflows and reporting across global maritime security operations — the interface no longer standing between an analyst and the answer."),
    ('pull', 'Outcome — one view', 'Disparate sources, one real-time view — <span class="mag">built to make the next decision faster</span>.'),
    ('comment', '[OUTCOME PLACEHOLDER — Notion Needs Review=YES. Tier 2 (qualitative). Class 2 (adoption by analysts/field teams). Verify operational metrics if NCIS will share them (response-time / workflow-speed deltas). Internal marker — not rendered.]'),
  ],
  'next': ['telus-support', 'hall-constructors'],
},
{
  'slug': 'telus-support',
  'title': 'TELUS Support Case Study — Self-Serve Redesign | POWER SHIFTER',
  'meta': 'How POWER SHIFTER redesigned TELUS Support self-serve — a 30% drop in call volume and over $600K saved in year one, with governed content to keep it that way.',
  'eyebrow': 'Digital · TELUS Support',
  'h1': "A self-serve redesign that took $600K out of the first year's support costs",
  'subvoice': 'More help articles had made support harder, not easier — so we culled, governed, and redesigned until customers could solve it themselves.',
  'role': 'Strategy · Co-design · UX research &amp; design · UI · Contentful',
  'cat': 'Digital', 'client': 'TELUS Digital', 'sector': 'Telecom · Customer support',
  'services': 'Strategic planning · Co-design workshops · UX research &amp; design · UI · Usability testing · Web &amp; Contentful development · Measurement strategy',
  'platform': 'Contentful · Web',
  'body': [
    ('h2', 'the brief.'),
    ('p', "With an average cost of $10–15 per customer service call, it is not surprising to see organizations invest in comprehensive online self-serve experiences. When TELUS Digital needed to optimize their online Support experience, we ran a design and technology overhaul that produced a 30% drop in call centre volume and over $600,000 in savings in the first year."),
    ('p', "Three years on, a company-wide design system change — and a growing pile of support articles with no governance over how they were written or categorized — made content hard for customers to find. Call volumes started climbing again. We stepped back in to streamline the experience a second time."),
    ('pull', 'Brief — the economics', 'At $10–15 a call, <span class="mag">every problem solved online is money that stays in the business</span>.'),
    ('h2', 'the challenge.'),
    ('p', "The first engagement was a redesign problem. The second was a content and governance problem wearing a UX disguise: TELUS had more support articles than ever, multiple product owners updating them, and no shared rules holding the whole library together. More content was making support harder, not easier — and the rising call volume was the symptom."),
    ('h2', 'the process.'),
    ('p', "We didn't start by redesigning pages. We started by culling and reorganizing the existing content, then built a comprehensive governance program so the growing content team — with its multiple product owners — could keep the library coherent as it scaled. Design followed strategy, not the other way around."),
    ('h2', 'the solution.'),
    ('h3', 'a powerfully simple redesign.'),
    ('p', "We designed a new experience that made it easier to find support content across touchpoints — including from pages outside TELUS Support — with clearer guidance through the Support journey, updated categorization, and more readable articles."),
    ('h3', 'behind the build.'),
    ('p', "A strong customer experience needed an equally strong foundation for the content stakeholders behind it. Contentful checked every box and simplified the otherwise painful job of migrating thousands of articles off the legacy CMS — chosen because the content team's flexibility was as much the product as the customer-facing pages."),
    ('h2', 'the outcome.'),
    ('p', "The first improvement enabled 30% more customers to solve their issues on the website, and over 70% of Support visitors arriving from 'Contact Us' never returned to that page — a clean signal they'd resolved the problem online."),
    ('p', "The optimization built on those numbers: a 9% reduction in overall support costs, 9% fewer Support visitors landing on 'Contact Us,' and a 17% lift in article traffic. A simpler experience, a governed content strategy, and a robust platform — saving customers a call for help for years to come."),
    ('pull', 'Outcome — solved online', "Seven in ten customers who reached the 'Contact Us' page <span class=\"mag\">never came back — they'd already solved it</span>."),
    ('quote', "The calibre of talent at Power Shifter is truly impressive. Having them as part of my team lets me handle communications and stakeholder management on the project with the peace of mind that my Scrum Master, Developers, Designers, and Data Analysts (Power Shifter team) have the rest of the project details and deliverables under control and operating at the highest quality. I couldn't ask for a better, higher performing team.", 'Samantha Bahrini', 'Product Manager', 'TELUS Digital'),
  ],
  'next': ['telus-rewards', 'angel-oak-home-loans'],
},
{
  'slug': 'luxxee',
  'title': 'luxxee Case Study — Luxury Watch Search Engine | POWER SHIFTER',
  'meta': 'How POWER SHIFTER co-founded luxxee — a luxury watch search engine of 170,000+ listings — and proved the model with its first high-value sales and organic rankings.',
  'eyebrow': 'Digital · luxxee',
  'h1': "We didn't just build the product. We co-founded it, equity and all",
  'subvoice': 'A gap in the luxury-watch market we believed in enough to co-found — equity, risk, and all.',
  'role': 'Digital strategy · UX/UI · Brand · React engineering',
  'cat': 'Digital', 'client': 'luxxee (POWER SHIFTER venture)', 'sector': 'Luxury e-commerce · Watches',
  'services': 'Digital strategy · UX research &amp; design · UI · Brand development · Content strategy · Cloud engineering · React development',
  'platform': 'React · Cloud · Affiliate commerce',
  'body': [
    ('h2', 'the brief.'),
    ('p', "When we identified a gap in the luxury watch market, we did something most agencies never do: we took on the risk ourselves. POWER SHIFTER's CEO, JP Holecka, partnered with industry leaders to bring luxxee — an investor-backed luxury e-commerce product — to life, building an intelligent platform that lets consumers make informed purchases in a space designed to keep them in the dark."),
    ('pull', 'Brief — skin in the game', 'Most agencies build the product. On luxxee, <span class="mag">we put up a third of the equity</span>.'),
    ('h2', 'the challenge.'),
    ('p', "A luxury watch search engine isn't a storefront — it's a product that demands deep knowledge of both software and the watch market, built and proven on a startup's finite budget while the pressure to prove the thesis runs high. We weren't briefed on those constraints. We lived them, as one-third equity partners on the hook for the outcome."),
    ('h2', 'the process.'),
    ('p', "We applied decades of agency learnings to build a search engine that required fluency in both product development and the luxury space. As COVID-19 accelerated the shift to digital buying, we steered the build toward e-commerce patterns tailored to that new reality — moving luxxee from a strong idea to a product in market, fast."),
    ('h2', 'the solution.'),
    ('h3', "a one-stop shop for the world's top watch brands."),
    ('p', "luxxee is a powerful search engine bringing together the best luxury watches from across the web — Rolex, Omega, Tudor, Breitling and other renowned names — so consumers can compare and buy with full information. The catalogue runs to over 170,000 items, with an average resale value between $3,000 and $150,000."),
    ('h3', 'a content strategy that drives affiliate sales.'),
    ('p', 'Alongside the platform, we built luxxee Magazine — a luxury e-commerce publication organized around the idea of "time" — to engage consumers across the funnel and establish luxxee as the category\'s go-to expert, directing readers to listings and driving affiliate sales. We ran it on an SEO strategy from our search and content partners at Status Bureau, and executed it to the letter — the discipline of following a search strategy precisely is what lets it actually compound.'),
    ('p', "Being on the hook for luxxee's success — not only as agency of record but as one-third equity investment partners — gave us the experience to expedite development and move faster than our competitors. We've felt firsthand what a startup faces building a product from the inside out, which is exactly why we can do it for clients now."),
    ('h2', 'the outcome.'),
    ('p', "luxxee went to market and proved the thesis early. The first two sales — $18,000 USD Rolexes moved through our eBay partnership — were the product-market-fit signal we were looking for: confirmation that consumers would transact at the high end through the platform."),
    ('p', 'Those sales didn\'t come from nowhere. Following Status Bureau\'s SEO strategy precisely, luxxee Magazine\'s organic results arrived almost exactly on the predicted timeline — close to the week they\'d forecast — with the publication starting to outrank terms as competitive as "Rolex" in organic search. The timing lines up: that search visibility and those first high-value sales are very likely connected.'),
    ('p', "<em>(Catalogue size and resale values describe the product. Speed-to-market, those first transactions, a live affiliate engine, and organic rankings on category-defining terms are the result.)</em>"),
    ('pull', 'Outcome — proof', 'luxxee Magazine started outranking terms as competitive as <span class="mag">"Rolex"</span> — right on the forecast timeline.'),
    ('pull', 'Outcome — first blood', 'Two $18,000 Rolexes sold through our eBay partnership — <span class="mag">the product-market-fit signal we needed</span>.'),
    ('quote', "You can't make the claim to really know the challenges of a startup until you've been a start up. We've been a startup — we understand your needs at a deeper level.", 'JP Holecka', 'CEO', 'POWER SHIFTER'),
  ],
  'next': ['5x5', 'phinity'],
},
{
  'slug': 'bc-parks-foundation',
  'title': 'BC Parks Foundation Case Study — DiscoverParks.ca Rebuild | POWER SHIFTER',
  'meta': 'How POWER SHIFTER rescued a failed launch and rebuilt DiscoverParks.ca into a user-first, foundation-managed platform for exploring and booking BC parks.',
  'eyebrow': 'Digital · BC Parks Foundation',
  'h1': 'Rescuing a launch that had already failed once',
  'subvoice': 'A launch that had already failed once — rebuilt user-first, and built to win back the trust the first attempt broke.',
  'role': 'Product management · UX research &amp; design · UI · Web development',
  'cat': 'Digital', 'client': 'BC Parks Foundation', 'sector': 'Non-profit · Parks &amp; recreation',
  'services': 'Product management · UX research &amp; design · UI · Web development · PM · Design sprints · QA · Ongoing development',
  'platform': 'Web platform · CMS',
  'body': [
    ('h2', 'the brief.'),
    ('p', "BC Parks Foundation wanted an intuitive, engaging platform for British Columbians to explore and book park experiences. What they had was the first vendor's clunky, admin-unfriendly, user-confusing version — and a stakeholder group that had lost faith. The brief was as much about restoring trust as building software: deliver the original vision, this time user-first and future-ready."),
    ('pull', 'Brief — the real ask', "The brief wasn't only to build the platform. It was to <span class=\"mag\">rebuild the trust the first attempt broke</span>."),
    ('h2', 'the challenge.'),
    ('p', "The starting point was a broken system and a skeptical client. The existing platform was confusing for users and admins alike, rigid and overcomplicated, and failing at core jobs like event booking and self-guided activities. Stakeholders were frustrated by money already spent — so the work had to prove, early and visibly, that this time would be different."),
    ('h2', 'the process.'),
    ('p', "We led with discovery and transparency. Deep interviews and workshops re-established alignment, and we rebuilt confidence — the only way it can be rebuilt — through agile delivery and incremental wins that stakeholders could see. Technical audits and user research with both seasoned parkgoers and first-time explorers told us where the old system actually failed; prototype testing validated the navigation, booking, and self-guided journeys before we committed to them. The governing principle: usability over technical constraint, every time the two collided."),
    ('h2', 'the solution.'),
    ('h3', 'a scalable, user-first platform.'),
    ('p', "We rebuilt DiscoverParks.ca on a flexible, scalable foundation, replacing the rigid legacy system. Event booking and navigation were streamlined to cut the friction that had stalled the original; an intuitive CMS put content control back in the foundation's hands, and the brand's digital identity was strengthened to reinforce credibility with parkgoers. We took an MVP-first approach — launching, learning from real-world feedback, and improving — rather than betting everything on a single big release."),
    ('h2', 'the outcome.'),
    ('p', "The headline here is recovery: a failed vendor investment turned into a working, trusted platform — a cost-avoidance outcome before it's anything else. Simplified booking flows increased engagement and participation; an intuitive CMS freed the foundation's team to manage the platform independently; and stakeholders regained confidence in a product that finally aligned with their mission. The foundation is left with a future-ready foundation built to adapt as needs grow."),
    ('pull', 'Outcome — recovery', 'A failed vendor investment, turned into <span class="mag">a platform people trust</span> — recovery is the result.'),
    ('comment', '[OUTCOME PLACEHOLDER — Notion Needs Review=YES. Tier 2 (qualitative). Class 2/3/4/7. Verify live status of DiscoverParks.ca + any engagement/booking figures the foundation will share. Internal marker — not rendered.]'),
  ],
  'next': ['nva', 'bcw'],
},
{
  'slug': '5x5',
  'title': '5x5 Technologies Case Study — Webflow Site for the Raise | POWER SHIFTER',
  'meta': 'How POWER SHIFTER built 5x5 Technologies a 3D, animated Webflow site that showed their AI infrastructure analytics — and shipped ahead of the fundraising window.',
  'eyebrow': 'Digital · 5x5 Technologies',
  'h1': "A website that didn't just tell the story, it showed it — built for the fundraise",
  'subvoice': "Technology that's dimensional and in motion — given a website that shows it, not just tells it, in time for the raise.",
  'role': 'Digital strategy · UX/UI · Art direction · Development',
  'cat': 'Digital', 'client': '5x5 Technologies', 'sector': 'InfraTech · AI analytics',
  'services': 'Digital strategy · UX research &amp; design · UI · Art direction · Content strategy · Measurement strategy · Development',
  'platform': 'Webflow · 3D / Lottie',
  'body': [
    ('h2', 'the brief.'),
    ('p', "5x5 Technologies is an InfraTech company providing AI-powered analytics for industrial structures in the built world — drones collecting data, precise 3D digital twins you can inspect from every angle. The technology is dimensional and in motion. A flat, text-heavy website couldn't represent it."),
    ('p', "Like many startups, 5x5 had poured its early energy into building the technology and validating product-market fit, developing a restructured brand identity on a parallel track. They came to us to launch it. The site had to do more than tell investors and B2B customers the company's story — it had to show them."),
    ('pull', 'Brief — in motion', 'The technology is dimensional and in motion — <span class="mag">a flat website couldn\'t represent it</span>.'),
    ('h2', 'the challenge.'),
    ('p', "The company had outgrown its original website, and the timing wasn't flexible: the site had to be ready for the maturity and sophistication a fundraising round demands. That meant rebuilding from the homepage out — replacing text walls and static imagery with 3D graphics and dynamic animation — while keeping the build fast enough to hit the window and collaborative enough that 5x5's team could shape copy and content alongside us."),
    ('h2', 'the process.'),
    ('p', "We started with the investor-facing pages — the ones that had to foreground sophistication and attract interest immediately — and rebuilt the homepage from the ground up. From there we worked outward into the detailed product pages, holding the same interactive quality across every screen, then tuned all of it for a cohesive experience on desktop and mobile."),
    ('h2', 'the solution.'),
    ('p', "We knew that 5x5's website needed to represent their technology in a novel way — a static website wasn't going to cut it. Tasked with delivering a site that put the brand front and centre in time for fundraising, we relied on a flexible low/no-code platform."),
    ('p', "Webflow was the best choice for this project. It allowed for fast prototyping, collaborative content creation, and advanced animations using built-in Lottie integration — vital for showing dimensionality in motion. The no/low-code structure minimized dev time so the team could focus on building an immersive experience, and it let us work seamlessly with a client who wanted a high degree of collaboration on copy and content."),
    ('p', "Above all, we made the end product clearly articulated — through both text and design — to position 5x5 as a leading force in the infrastructure analytics market, with value props and differentiators a prospective customer or investor could grasp from the first screen."),
    ('h2', 'the outcome.'),
    ('p', "The site shipped on the urgent timeline it was built for — ready ahead of the fundraising window. And the round it was built for closed: 5x5 got what they needed. The team was left with a CMS structured to manage content and growth without coming back to us."),
    ('pull', 'Outcome — the raise', 'The site was built for the fundraise. <span class="mag">The fundraise closed.</span>'),
    ('quote', "I challenged Power Shifter to create a website backed by a powerful CMS, built for growth, structured for easy content changes, and with a design ethos unlike anything else seen in our industry. They certainly delivered.", 'Chris Fawcett', 'Chief Marketing Officer', '5x5 Technologies Inc.'),
  ],
  'next': ['luxxee', 'delta-controls'],
},
{
  'slug': 'phinity',
  'title': 'Phinity Case Study — D2C Pool-Care Commerce | POWER SHIFTER',
  'meta': 'How POWER SHIFTER helped Sigura test direct-to-consumer with Phinity — a Shopify Plus and subscription platform that launched in time for pool season.',
  'eyebrow': 'Digital · Phinity',
  'h1': 'A pool-care giant tested a direct-to-consumer model, and it became the business',
  'subvoice': "Not 'build a store' but 'prove a manufacturer can sell straight to consumers' — with a real launch and the parent company watching.",
  'role': 'Strategy · UX research &amp; design · Shopify Plus · Contentful',
  'cat': 'Digital', 'client': 'Phinity (by Sigura)', 'sector': 'D2C · Pool care',
  'services': 'Strategic planning · Product-market fit · Co-design workshops · UX research &amp; design · UI · Shopify Plus · Contentful',
  'platform': 'Shopify Plus · Contentful',
  'body': [
    ('h2', 'the brief.'),
    ('p', "Phinity is a complete Smart Water Care system that makes chlorine and saltwater pool maintenance simple. It was started by parent company Sigura to test a new direct-to-consumer model — and Sigura came to us to build the e-commerce system and marketing site that would give the new D2C brand its best chance of success."),
    ('p', 'The brief wasn\'t really "build a store." It was "validate whether a manufacturer can sell straight to consumers" — with a real product, a real launch, and a parent company watching to decide whether this becomes the future of the business.'),
    ('pull', 'Brief — the real test', 'The brief wasn\'t build a store. It was <span class="mag">prove a manufacturer can sell straight to consumers</span>.'),
    ('h2', 'the challenge.'),
    ('p', "Three things had to work at once for this to succeed: the supply chain, customer service, and the Shopify Plus application. None of them was fully in our hands — the work ran across two other agencies and multiple stakeholders — and the whole pilot was pinned to an immovable deadline: testing in time for pool season. Miss the season, miss the year."),
    ('h2', 'the process.'),
    ('p', "We took a human-centric approach and worked the seams between stakeholders, not just the interface. With the season bearing down, we validated messaging and pricing through live A/B tests on the site, and partnered with the supply team to streamline delivery so products reached customers' doors. Design is more than aesthetics: based on our research, we proposed revisions to existing prototypes that made the brand and product more mobile-friendly, more editable, and faster to develop."),
    ('h2', 'the solution.'),
    ('h3', 'a customer-centric subscription service.'),
    ('p', "We used the website itself as a testing instrument — running A/B tests on bundles and messaging so real customer data, not assumption, told us how to make subscribing to pool maintenance feel fast and simple."),
    ('h3', 'a robust Contentful and Shopify Plus application.'),
    ('p', "We built an interactive, user-friendly site ready for a critical launch date and flexible enough to change on findings — Contentful for the marketing pages, Shopify Plus plus third-party integrations for commerce."),
    ('h2', 'the outcome.'),
    ('p', "Sigura kicked off pool season with an entirely new business model live. Just one month after launch, the data showed more visitors arriving to shop than to learn — a sign people felt educated enough to buy on the spot. The company's C-suite was delighted with the lift in brand awareness, product knowledge, and the execution of the build, and our continuing work means each season's insights feed the next."),
    ('pull', 'Outcome — the signal', 'One month in, <span class="mag">more visitors came to buy than to learn</span> — the model was working.'),
    ('comment', '[OUTCOME PLACEHOLDER — Notion Needs Review=YES. Tier 2 (qualitative). Class 6 (post-launch business events). Verify whether the D2C pilot was adopted as Sigura\'s ongoing model + scope of expansion. Internal marker — not rendered.]'),
    ('quote', "Thrilled with the work Power Shifter has done under very tight timelines and customizing the solution for our unique needs. Very collaborative and customer-centric design thinking led to a great end product that has been very well received by our customers.", 'Achin Kansal', 'Head of Direct to Consumer', 'Sigura Water'),
  ],
  'next': ['angel-oak-home-loans', 'telus-support'],
},
{
  'slug': 'nva',
  'title': 'NVA Case Study — Veterinary Brand Design System | POWER SHIFTER',
  'meta': "How POWER SHIFTER unified NVA's 1,000+ independently run veterinary hospitals into one scalable, persona-driven design system their internal team could ship.",
  'eyebrow': 'Digital · NVA',
  'h1': 'One brand story across 1,000+ hospitals, without flattening any of them',
  'subvoice': 'One brand story across 1,000+ independently run hospitals — unified without flattening any of them.',
  'role': 'Product management · UX research &amp; design · UI · Design system',
  'cat': 'Digital', 'client': 'National Veterinary Associates', 'sector': 'Veterinary · Multi-brand',
  'services': 'Product management · UX research &amp; design · UI · PM · Design sprints',
  'platform': 'Design system · Web',
  'body': [
    ('h2', 'the brief.'),
    ('p', "NVA is one of the world's largest veterinary organizations, and it needed to pull a fragmented digital ecosystem into a single, cohesive platform — while balancing corporate brand consistency against the autonomy of 1,000+ independently operated hospitals. The site had to serve genuinely different audiences (job seekers, prospective clinic partners, internal staff, industry peers) and ship as a flexible design system NVA's own development team could implement."),
    ('pull', 'Brief — the balance', 'Unify 1,000+ independently run hospitals under one brand — <span class="mag">without flattening any of them</span>.'),
    ('h2', 'the challenge.'),
    ('p', "A decentralized network is a brand problem and an architecture problem at once. The organically grown web ecosystem was diluting the brand and confusing users; the journeys for each audience were tangled together; and the people-first, local identity that defines NVA couldn't be sacrificed to corporate uniformity. On top of that, the build would happen in-house — so the deliverables had to be rigorous enough that an internal team could execute them without us in the room."),
    ('h2', 'the process.'),
    ('p', "We ran strategic alignment sessions with NVA's marketing and IT teams to set business goals, prioritize audiences, and map the content architecture, then designed around three primary personas — job seekers, potential veterinary partners, and existing community members — each with its own clear, empathetic pathway. We accounted for the real integrations the platform depends on (Averture for applicant tracking, Yext for location services, Weglot for French-language support), carved out region-specific content zones to differentiate NVA Canada, and produced annotated, developer-ready files so the internal team could build from them directly."),
    ('h2', 'the solution.'),
    ('h3', 'a modular system built for global scale.'),
    ('p', "We delivered a full UX and UI redesign as a modular, persona-driven design system — flexible content publishing, regional customization to balance global and local messaging, and a foundation built to grow and localize. The handoff files were optimized for NVA's internal dev workflows, so the design could become a live site in their hands, not ours."),
    ('h2', 'the outcome.'),
    ('p', "NVA's brand story now reads consistently across the U.S., Canada, and international markets, with content discoverability and audience journeys clarified, and an internal team able to publish and manage on its own. The fragmented ecosystem was consolidated into one cohesive platform — a countable reduction — and the system was built so NVA's people-first, decentralized philosophy survives inside a unified frame."),
    ('pull', 'Outcome — built to hand off', "Built so NVA's internal team could ship it from our handoff files — <span class=\"mag\">and own it after</span>."),
    ('comment', '[OUTCOME PLACEHOLDER — Notion Needs Review=YES. Tier 2 (qualitative). Class 1/2/7. Verify exact count of legacy sites consolidated + confirm internal team shipped from handoff files. Internal marker — not rendered.]'),
  ],
  'next': ['bc-parks-foundation', 'telus-support'],
},
{
  'slug': 'bcw',
  'title': "BC Women's Health Foundation — Awareness Microsite | POWER SHIFTER",
  'meta': "How POWER SHIFTER turned BC Women's Health Foundation's research into a shareable microsite — 3,500 visitors in under 20 days and coverage on CTV, Global, and CBC.",
  'eyebrow': 'Digital · BC Women’s Health Foundation',
  'h1': 'A research report turned into a campaign that hit the news',
  'subvoice': "A dense research report, turned into a campaign people couldn't help but share — and the news couldn't ignore.",
  'role': 'Strategy · UX research &amp; design · UI · Product engineering',
  'cat': 'Digital', 'client': "BC Women's Health Foundation", 'sector': "Non-profit · Women's health",
  'services': 'Strategic planning · Co-design workshops · UX research &amp; design · UI · Product engineering · Web &amp; mobile development',
  'platform': 'Webflow microsite',
  'body': [
    ('h2', 'the brief.'),
    ('p', "BC Women's Health Foundation is the province's largest non-profit dedicated to equitable access to the full spectrum of women's health. Ahead of releasing their report on the socioeconomic impacts of COVID-19 on women's health, the foundation asked us to expand its reach and impact."),
    ('p', "A dense report doesn't move people. The challenge was to take rigorous research and make it land emotionally — to turn data into something a person would read, feel, and pass on."),
    ('pull', 'Brief — make it land', "A dense report doesn't move people. <span class=\"mag\">We had to make the data land emotionally.</span>"),
    ('h2', 'the challenge.'),
    ('p', "The report mattered, but reports get skimmed and forgotten. To create real awareness, the work had to do two things at once: distil the findings so someone could grasp the message whether or not they read the full document, and make those findings shareable enough to travel beyond the foundation's own audience — all on a timeline tied to the report's release."),
    ('h2', 'the process.'),
    ('p', "We ran user research, tested our hypotheses, and simplified the report down to the messages that evoked the strongest emotion, pairing each with a bold visual treatment. Every colour, image, and word served one purpose: to move a reader to act. Because the report's timing was fixed, we needed speed without sacrificing production value."),
    ('h2', 'the solution.'),
    ('h3', 'a bold, scannable microsite.'),
    ('p', "We built an interactive digital product in Webflow so visitors could glean the most important information whether or not they read the full report — an easily navigable platform that let people engage with the content resonating most with them."),
    ('h3', 'designed for sharing.'),
    ('p', "Awareness depended on people spreading the stories themselves. We turned anecdotes and facts into ready-made social graphics with Facebook, Twitter, LinkedIn, and Instagram sharing built in, making it effortless to push real quotes and credible data into personal networks."),
    ('p', "We chose Webflow for the speed: within a few days of handing the developer the designs, the team could view and iterate on the live microsite — essential given the report's timing."),
    ('h2', 'the outcome.'),
    ('p', "Less than 20 days after launch, the microsite had drawn 3,500 visitors, with hundreds sharing the social graphics to expose the campaign to thousands more. It earned recognition from Awwwards — an honourable mention in the website category and a Mobile Excellence award, which celebrates work that raises mobile web standards through design and performance. Major news networks including CTV, Global, and CBC featured Unmasking Gender Inequity on air."),
    ('p', "The foundation positioned itself as a thought leader and changemaker driving the conversation on systemic gender inequity — and built the platform to scale, adding two further educational initiatives to the site since launch."),
    ('pull', 'Outcome — it travelled', '3,500 visitors in under 20 days, then <span class="mag">CTV, Global, and CBC put it on the news</span>.'),
    ('quote', "Talent, commitment, and innovation. We have been really inspired by the collective Power Shifter team – their individual talents, team camaraderie, and ability to think outside of the box at every step really drove this project to the success we achieved.", 'Victoria Gay', 'Senior Director, Strategy', "BC Women's Health Foundation"),
  ],
  'next': ['5x5', 'bc-parks-foundation'],
},
{
  'slug': 'delta-controls',
  'title': 'Delta Controls Case Study — IoT Sensor Configuration | POWER SHIFTER',
  'meta': "How POWER SHIFTER took Delta Controls' O3 sensor setup from hardware to cloud — cutting configuration time from 5 minutes to 90 seconds, even offline in the field.",
  'eyebrow': 'Digital · Delta Controls',
  'h1': 'Sensor setup that took 5 minutes now takes 90 seconds',
  'subvoice': 'A hardware company stepping into software — sensor setup taken from the job site to the cloud, five minutes down to ninety seconds.',
  'role': 'Strategy · Co-design · UX/UI · Product engineering · GCP',
  'cat': 'Digital', 'client': 'Delta Controls', 'sector': 'IoT · Building controls',
  'services': 'Strategic planning · Co-design workshops · UX research &amp; design · UI · Product engineering · Web &amp; mobile · Google Cloud architecture',
  'platform': 'Google Cloud · Web + mobile',
  'body': [
    ('h2', 'the brief.'),
    ('p', "Delta Controls is a leading control manufacturer helping industries manage surveillance, lighting, cameras, and occupancy sensing. Ahead of launching their O3 Sensor Hub 2.0, they asked us to build a planning and configuration experience that would cut the time installers spend on-site and make the system faster to learn."),
    ('p', "The unstated stakes were bigger than convenience. Every minute an engineer spends configuring hardware on a job site is a cost — to Delta and to their customers. Reduce the on-site time and you change the economics of the whole product."),
    ('h2', 'the challenge.'),
    ('p', "This was a hardware company stepping deliberately into software. The configuration experience had to be easy enough to compress training, robust enough to run in the field — including the dead zones where there's no connectivity — and architected to scale across future products, not just this one hub. Expanding from hardware into cloud-based software is a new business, not a feature."),
    ('pull', 'Challenge — the economics', 'Every minute an engineer spends configuring hardware on-site is a cost — <span class="mag">cut it and you change the product\'s economics</span>.'),
    ('h2', 'the process.'),
    ('p', "We took a user-centric, design-thinking approach, working in co-design with Delta's team to build a robust Google Cloud IoT platform — chosen for the room it left to update and scale as the product line grew."),
    ('h2', 'the solution.'),
    ('h3', 'a powerful web application.'),
    ('p', "The web app lets engineers plan and configure O3 sensor hubs online, setting up and managing devices remotely instead of on-site. Everything created in the app is stored in the cloud; once hubs are connected, the platform delivers remote, real-time data insights and reporting."),
    ('h3', 'configuration that survives the field.'),
    ('p', "To handle on-site dead zones, the mobile app downloads everything it needs at login and lets the installer keep working offline, syncing to the cloud the moment data or WiFi returns. Installers can see which settings failed to sync and spot malfunctioning sensors through live, real-time readings from the device."),
    ('p', "By moving from hardware into cloud-based software, Delta laid the foundation for a new business model — one built to shift and grow as the technology does."),
    ('h2', 'the outcome.'),
    ('p', "With the web app, engineers manage sensor hubs online, reducing configuration time threefold: what once took 5 minutes now takes 90 seconds. Minimizing engineers' on-site involvement means significant cost savings for Delta Controls and its customers."),
    ('p', "The work was validated outside the building, too. Since launch, Delta Controls was awarded the Frost &amp; Sullivan 2020 Global Company of the Year Award for its hub — the citation calling the O3 Sensor Hub 2.0 a new industry benchmark — and the platform won Best UX for Product at the 2020 Vancouver User Experience Awards."),
    ('pull', 'Outcome — 3x faster', 'What once took five minutes <span class="mag">now takes ninety seconds</span>.'),
    ('quote', "The launch of the projects and the design phase has been impressive. Power Shifter is very strong at that, which a lot of others aren't.", 'Kevin Batdorf', 'Unitary Controls Line Manager / Senior Developer', 'Delta Controls'),
  ],
  'next': ['5x5', 'angel-oak-home-loans'],
},
{
  'slug': 'angel-oak-home-loans',
  'title': 'Angel Oak Home Loans Case Study — SEO Web Redesign | POWER SHIFTER',
  'meta': 'How POWER SHIFTER rebuilt Angel Oak Home Loans as an SEO-led Webflow platform for non-QM borrowers — driving a 40% lift in organic leads within 30 days.',
  'eyebrow': 'Digital · Angel Oak Home Loans',
  'h1': 'A site rebuilt around how people actually borrow, with leads to match',
  'subvoice': 'A mortgage site that was a brochure, rebuilt as an SEO-led sales engine for the borrowers most lenders ignore.',
  'role': 'UX research &amp; design · UI · Webflow · SEO',
  'cat': 'Digital', 'client': 'Angel Oak Home Loans', 'sector': 'Mortgage lending · Non-QM',
  'services': 'UX research &amp; design · UI · Web development · Design sprints · PM · No/low-code development',
  'platform': 'Webflow · SEO',
  'body': [
    ('h2', 'the brief.'),
    ('p', "Angel Oak Home Loans serves borrowers most lenders' websites ignore — self-employed applicants, investors, foreign nationals — through a portfolio of non-QM mortgage products. The opportunity was real; the digital front door wasn't built to capture it."),
    ('p', "Their previous site was technically outdated and hard to update, poorly optimized for the mortgage keywords that matter, disjointed for both traditional and non-traditional borrowers, and unable to support marketing campaigns. Every one of those is a leak in the funnel."),
    ('pull', 'Brief — engine or brochure', "A mortgage lender's website is a sales engine or it's a brochure. <span class=\"mag\">Theirs was a brochure.</span>"),
    ('h2', 'the challenge.'),
    ('p', "The hard part wasn't a redesign — it was making one site serve two very different borrowers without confusing either, while fixing a technical foundation that search engines couldn't read and marketing couldn't use. The site had to rank, convert, and keep up with campaigns the team would launch on their own."),
    ('h2', 'the process.'),
    ('p', "We worked with Angel Oak's team to align the experience with both traditional and underserved borrowers, then partnered with Flywheel Digital on the technical SEO foundation: clean URL architecture and internal linking, meta optimization and schema markup, and a custom branch locator keyed to area code. The build ran on Webflow for speed, responsiveness, and the security and easy content management the team needed to own it after handoff."),
    ('h2', 'the solution.'),
    ('h3', 'a site borrowers and search engines both understand.'),
    ('p', "The new Webflow build loads fast, reads cleanly to search, and lets Angel Oak update and manage content without a developer — closing the gaps that had made the old site invisible and inert."),
    ('h3', 'a landing-page engine for campaigns.'),
    ('p', "We built a no-code landing page generator so the team can launch paid social and Facebook campaigns instantly, with every page aligned to the same SEO standards as the core site — turning the website from a static asset into a campaign platform."),
    ('h2', 'the outcome.'),
    ('p', "The redesign was built to convert, and it did: a 40% increase in organic leads within the first 30 days of launch."),
    ('pull', 'Outcome — leads to match', 'A <span class="mag">40% lift in organic leads</span> inside the first 30 days.'),
    ('quote', "I don't know if I could be happier with how this turned out. I am so thankful that Webflow and the Power Shifter team were able to help us modernize our website. [...] The Power Shifter team are absolute professionals and Webflow will be doing any company a huge favour if they continue referring them.", 'John Bentley', 'VP Digital Marketing', 'Angel Oak Home Loans'),
  ],
  'next': ['telus-support', 'phinity'],
},
{
  'slug': 'telus-rewards',
  'title': 'TELUS Rewards Case Study — Loyalty Platform Design | POWER SHIFTER',
  'meta': 'How POWER SHIFTER designed and built the TELUS Rewards loyalty platform — uniting login, points, and CMS into one experience that launched 22% ahead of forecast.',
  'eyebrow': 'Digital · TELUS Rewards',
  'h1': 'The loyalty blueprint that launched 22% ahead of target',
  'subvoice': 'A loyalty platform sitting on three systems that never talked — built to feel like one, and launched 22% ahead of forecast.',
  'role': 'Solutions architecture · UX research · UI · Full-stack development',
  'cat': 'Digital', 'client': 'TELUS', 'sector': 'Telecom · Loyalty',
  'services': 'Solutions architecture · UX research · UI · Analytics strategy · Frontend &amp; backend development · Marketing strategy · PM',
  'platform': 'AWS · Contentful · Web',
  'body': [
    ('pull', 'The blueprint', 'Building loyalty takes more than points — <span class="mag">it takes a blueprint</span>.'),
    ('h2', 'the brief.'),
    ('p', "A telecom rewards program competes for attention against every other loyalty card in a customer's wallet. To matter, TELUS Rewards had to do three things at once: differentiate in a crowded market, feel intuitive for both members and the admins running it, and launch on an aggressive, deadline-driven timeline against TELUS's new digital standards."),
    ('p', "The hard part wasn't the front end. It was everything behind it. A rewards experience that looks simple is usually sitting on top of several systems that don't naturally talk to each other — and this one had to bring three together under enterprise security and accessibility requirements, with no room to slip the date."),
    ('h2', 'the challenge.'),
    ('p', "<strong>Three systems, one experience.</strong> The platform had to unite stacks that were never designed to operate as one:"),
    ('ul', [
      "<strong>The TELUS Account API</strong> for login and authentication, so members used the credentials they already trusted.",
      "<strong>Aimia's Rewards API</strong> for points balances, redemption, and activity — the live engine the whole program runs on.",
      "<strong>Contentful</strong> as the CMS, so TELUS could manage and evolve content without a developer in the loop.",
    ]),
    ('p', "On top of that: a deadline-driven launch held to TELUS's new digital standards, with WCAG 2.0 AA accessibility and enterprise-grade security as non-negotiable conditions, not finishing touches."),
    ('pull', 'Challenge — the hidden stack', "A rewards experience that looks simple is usually <span class=\"mag\">three systems that don't talk to each other</span>."),
    ('h2', 'the process.'),
    ('p', "We didn't treat this as one build. We treated it as a program with a sequence — and the sequence mattered, because each phase de-risked the next."),
    ('p', "<strong>Phase one — launch the platform.</strong> Stand up the member-facing site, prove the integrations under real load, hit the date."),
    ('p', "<strong>Phase two — equip the people behind it.</strong> A consumer launch is only half the system. The customer service reps fielding member questions were working out of fragmented legacy tools, so the next phase gave them a portal built for the job."),
    ('p', "<strong>Phase three — optimize for the long term.</strong> With the platform live and supported, we mapped the full member journey to find where activation and redemption were leaking, and rebuilt those moments to scale TELUS Rewards from a launched product into a durable loyalty ecosystem."),
    ('h2', 'the solution.'),
    ('h3', 'a seamless customer platform.'),
    ('p', "We designed and developed the customer-facing Rewards site to make three disconnected systems feel like one. Member identity flowed from the TELUS Account API, points and redemption came live from Aimia, and every piece of content was managed in Contentful — chosen because it let TELUS's own team ship and evolve content without engineering involvement. The build was responsive, mobile-first, and WCAG 2.0 AA–compliant, hosted on TELUS's own AWS environment for the security and scalability an enterprise loyalty program demands. It launched on time and on budget."),
    ('h3', 'a secure agent portal.'),
    ('p', "Then we turned to the people supporting members. We built a dedicated portal with SAML single sign-on for authorized agent access, giving CSRs a 360° member view — account search, history, and validated, permission-based points adjustments — in place of the fragmented workflows they'd been stitching together. The judgment here was simple: faster, more accurate support is a member experience too, just one the member never sees."),
    ('pull', 'Process — the unseen half', 'Faster, more accurate agent support is a member experience too — <span class="mag">just one the member never sees</span>.'),
    ('h3', 'optimizing the program end to end.'),
    ('p', "With the foundation in place, we mapped member journeys to locate friction, then rebuilt the weak points: a clearer activation flow with proper onboarding and triggered emails, a redemption experience improved with wishlists, tiers, and a refined catalogue, and an upgraded architecture with stronger reporting and tighter Aimia integration — engineered to carry the program's next stage of growth."),
    ('h2', 'the outcome.'),
    ('p', "TELUS Rewards launched on time, on budget, and ahead of plan."),
    ('ul', [
      "<strong>300K+ members enrolled within six months — 22% ahead of forecast.</strong> The platform didn't just hit its date; it beat its activation target out of the gate.",
      "<strong>100% of polled Rewards CSRs preferred the new agent portal</strong> to the legacy tools they'd replaced — a clean adoption signal from the people who use it every shift. In their words, the team was “amazed at the simple and more specific layout to help support customers.”",
      "<strong>Rewards members reported higher likelihood-to-recommend (L2R) scores</strong> across the enterprise than non-members — the program changing how customers feel about TELUS, not just what's in their points balance.",
    ]),
    ('p', "The optimization phase rebuilt activation and redemption to lift engagement and position the program for long-term ROI. TELUS's internal projections had the redesigned activation flow nearly tripling activation rates."),
    ('pull', 'Outcome — ahead of plan', "It didn't just hit its date — <span class=\"mag\">it beat its activation target by 22%</span> out of the gate."),
    ('comment', '[OUTCOME PLACEHOLDER — Notion Needs Review=YES. Tier 1. The "nearly triple activation" figure is a TELUS internal PROJECTION, not a measured phase-three result — verify actual activation/redemption lift before quoting. 300K+/22%-ahead enrollment + 100% CSR preference are stated results. Internal marker — not rendered.]'),
    ('quote', "I wanted to say a HUGE thank you to the Power Shifter team for making our site so user-friendly, with an incredibly clean design that really reflect the TELUS brand. The team was extremely helpful in answering our questions and was able to address and deploy several changes on a whim.", 'Sabrina Mah', 'Product Manager, Consumer Products &amp; Content', 'TELUS'),
  ],
  'next': ['telus-support', 'luxxee'],
},
]
